name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Uberspace
      url: https://wk-timer.us.silas229.name

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run typecheck

      - name: Run tests
        run: npm run test:run

      - name: Build application
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy .next directory to server
        run: |
          rsync -avz --delete .next/ ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.SERVER_PATH }}/.next/

      - name: Copy JS files to server
        run: |
          rsync -avz public/*.js ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }}:${{ vars.SERVER_PATH }}/public/

      - name: Deploy on server
        run: |
          ssh -T ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "cd ${{ vars.SERVER_PATH }} && git pull && npm install --save && supervisorctl restart wk-timer"

      - name: Wait for application to start
        run: sleep 10

      - name: Verify supervisor status
        run: |
          status_output=$(ssh -T ${{ vars.SERVER_USER }}@${{ vars.SERVER_HOST }} "supervisorctl status wk-timer")
          echo "$status_output"
          if echo "$status_output" | grep -q "RUNNING"; then
            echo "✅ wk-timer is running"
          else
            echo "❌ wk-timer is not running"
            exit 1
          fi

      - name: Test application accessibility
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" https://wk-timer.us.silas229.name)
          if [ "$response_code" -eq 200 ]; then
            echo "✅ Application is accessible and returned HTTP 200"
          else
            echo "❌ Application returned HTTP $response_code"
            exit 1
          fi
